SET client_encoding = 'UTF8';

DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE
);

CREATE TABLE customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   TEXT NOT NULL,
    email       TEXT NOT NULL UNIQUE,
    region      TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE products (
    product_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL
        REFERENCES categories(category_id),
    name        TEXT NOT NULL,
    price       NUMERIC(12, 2) NOT NULL
        CHECK (price >= 0),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE orders (
    order_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL
        REFERENCES customers(customer_id),
    order_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    status     TEXT NOT NULL
        CHECK (
            status IN (
                'new',
                'paid',
                'shipped',
                'completed',
                'cancelled'
            )
        )
);

CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT NOT NULL
        REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id    BIGINT NOT NULL
        REFERENCES products(product_id),
    quantity      INTEGER NOT NULL
        CHECK (quantity > 0),
    unit_price    NUMERIC(12, 2) NOT NULL
        CHECK (unit_price >= 0)
);

CREATE TABLE reviews (
    review_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL
        REFERENCES products(product_id),
    customer_id BIGINT NOT NULL
        REFERENCES customers(customer_id),
    rating      SMALLINT NOT NULL
        CHECK (rating BETWEEN 1 AND 5),
    title       TEXT NOT NULL,
    body        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_products_category
    ON products(category_id);

CREATE INDEX idx_orders_customer
    ON orders(customer_id);

CREATE INDEX idx_orders_date
    ON orders(order_date);

CREATE INDEX idx_orders_status
    ON orders(status);

CREATE INDEX idx_order_items_order
    ON order_items(order_id);

CREATE INDEX idx_order_items_product
    ON order_items(product_id);

CREATE INDEX idx_reviews_product
    ON reviews(product_id);

CREATE INDEX idx_reviews_customer
    ON reviews(customer_id);

CREATE INDEX idx_reviews_created_at
    ON reviews(created_at);