CREATE SCHEMA IF NOT EXISTS monitoring;

CREATE TABLE IF NOT EXISTS monitoring.pipeline_metrics (
    metric_id BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    collected_at TIMESTAMPTZ NOT NULL
        DEFAULT now(),

    pg_active_connections INTEGER NOT NULL,
    pg_tps NUMERIC(14, 3) NOT NULL,
    pg_database_size_bytes BIGINT NOT NULL,

    ch_rows BIGINT NOT NULL,
    ch_qps NUMERIC(14, 3) NOT NULL,
    ch_min_active_replicas INTEGER NOT NULL,
    ch_replication_queue BIGINT NOT NULL,

    manticore_documents BIGINT NOT NULL,
    manticore_search_ms NUMERIC(14, 3) NOT NULL,

    orders_processed BIGINT NOT NULL,
    reviews_processed BIGINT NOT NULL,
    last_sync TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS
    idx_pipeline_metrics_collected_at
ON monitoring.pipeline_metrics(collected_at DESC);