upstream clickhouse_http {
    server ch-s1-r1:8123 max_fails=2 fail_timeout=10s;
    server ch-s1-r2:8123 max_fails=2 fail_timeout=10s;
    server ch-s2-r1:8123 max_fails=2 fail_timeout=10s;
    server ch-s2-r2:8123 max_fails=2 fail_timeout=10s;

    keepalive 32;
}